### ISSUE TITLE
Beetle USB support

### ISSUE THREAD

**Issue by eried** [mofosyne/arduino-gameboy-printer-emulator#11]
Hi! This is awesome, I got it working on a micro without issues, however I was trying to make it work on a Beetle (like a Digispark but with 32u4) but the Gameboy does not sees the printer :/ , which pins would be your recommended replacements for the original ones?: 

![image](https://user-images.githubusercontent.com/1091420/76670437-d1eeb700-6590-11ea-9108-ccea88cee54b.png)

Is the interrupt pin the only requeriment?

**Comment by mofosyne** [comment]
Yes the interrupt pin is the only requirement, since this is manually checking the edge of each clock for each bit.

**Comment by eried** [comment]
:) it worked fine, I ended trying different pins until it worked

twitter.com/eried/status/1238774188623699969

**Comment by mofosyne** [comment]
Awesome, maybe tell me what pins worked and I'll add it to the instructions.

**Comment by eried** [comment]
Oh, actually I checked the code and I used a small leonardo board. Not the beetle at the end
