### ISSUE TITLE
Print Error #02 in Game Boy Camera

### ISSUE THREAD

**Issue by slashinfty** [mofosyne/arduino-gameboy-printer-emulator#28]
I have wired up an arduino nano, uploaded the program, and set the baud rate. When I attempt to print, I get "Print Error #02," which translate to "Universal Game Link cable is incorrectly connected."

**Comment by mofosyne** [comment]
Join our telegram for some support. We've been getting regular feedback that it is working, so it's likely to be a wiring error on your end.

**Comment by mofosyne** [comment]
Telegram invite https://t.me/gameboycamera

**Comment by mofosyne** [comment]
Were you trying to print pokemon? If so was it only half an image you got? Just tested further and got something like

![image](https://user-images.githubusercontent.com/827793/88665584-2fd80180-d122-11ea-8e8c-ddb259d2e009.png)

**Comment by mofosyne** [comment]
I assume all is well now. Feel free to reopen this ticket. V2 is out now
