### ISSUE TITLE
Decoder that handle compression and palette swap

### ISSUE THREAD

**Issue by Raphael-Boichot** [mofosyne/arduino-gameboy-printer-emulator#34]
All-in-one package : emulator for arduino, decoder that handle compression and palette swap, compatibility list and documentation used.

Enjoy.

Raphaël

[Game_boy_printer_emulator_for_all_games.zip](https://github.com/mofosyne/arduino-gameboy-printer-emulator/files/5071186/Game_boy_printer_emulator_for_all_games.zip)

**Comment by Raphael-Boichot** [comment]
Update of the code with consensual output format and updated compatibility list

[Game_boy_printer_emulator_for_all_games.zip](https://github.com/mofosyne/arduino-gameboy-printer-emulator/files/5075271/Game_boy_printer_emulator_for_all_games.zip)

**Comment by mofosyne** [comment]
added for v2
