### ISSUE TITLE
Issue with parse mode and compressed data

### ISSUE THREAD

**Issue by Raphael-Boichot** [mofosyne/arduino-gameboy-printer-emulator#39]
Hello.

I discovered that the data sent by the emulator V2 in parse mode are not accurate for compressed games.

The capture ressemble one of your first attempt to embed decompression in the emulator. I think you've merged an old version of code for parse mode.

[Parse_Pokémon_Trading_Card.txt](https://github.com/mofosyne/arduino-gameboy-printer-emulator/files/5099143/Parse_Pokemon_Trading_Card.txt)

![télécharger](https://user-images.githubusercontent.com/63796796/90687719-8e9a2200-e26d-11ea-9090-878f74803104.png)

**Comment by mofosyne** [comment]
If i recall, this issue is now fixed

**Comment by Raphael-Boichot** [comment]
To what I remember, compressed mode was just not supported on Arduino for
memory/speed issue, but OK with ESP devices. This was the only issue
reported.

Raphaël

**Comment by mofosyne** [comment]
Well if I understand correctly, raw mode has full support for compressed stuff. So one strategy could be to just force everyone to use raw mode instead.

**Comment by Raphael-Boichot** [comment]
I do not remind exactly as I have no access to the discussion on the
Discord Game Boy Camera any more. I think you let parse mode for
compatibility reasons with some converters.

**Comment by mofosyne** [comment]
Done, V3 now is raw mode by default.
