### ISSUE TITLE
New images for the CrapPrinter story

### ISSUE THREAD

**Issue by Raphael-Boichot** [mofosyne/arduino-gameboy-printer-emulator#44]
Hello, could you intergrate these pictures into the folder for the CrapPrinter story (I do not have rights). I will then complete the story in the Read.me

![pixel_fit](https://user-images.githubusercontent.com/63796796/90987299-2a879e80-e58a-11ea-8f8b-1ac100bf7be9.png)
![Crap](https://user-images.githubusercontent.com/63796796/90987292-2065a000-e58a-11ea-8d2f-e785e8f752f4.png)
![Crap2](https://user-images.githubusercontent.com/63796796/90987297-278cae00-e58a-11ea-9881-652a4654506c.png)
![Crap3](https://user-images.githubusercontent.com/63796796/90987298-29ef0800-e58a-11ea-83b8-71f20227883b.png)

Thanks !

**Comment by mofosyne** [comment]
Now moved to https://github.com/mofosyne/GameboyPrinterPaperSimulation with the images you provided.
