### ISSUE TITLE
No need to splice a link cable - 3D print your own plug :)

### ISSUE THREAD

**Issue by markostamcar** [mofosyne/arduino-gameboy-printer-emulator#45]
Great work! We will use this at our non-profit Computer Museum to e-mail Game Boy Camera photos to visitors.

I designed a plug for DMG-01 that uses male dupont jumper wires:
https://www.thingiverse.com/thing:4685189

![Link Port plug](https://cdn.thingiverse.com/assets/5b/94/a8/a2/57/PXL_20201212_101502387.PORTRAIT.jpg)

**Comment by markostamcar** [comment]
... and here is how I implemented the "UI" using an old VT320 terminal:

![VT320](https://i.imgur.com/OfxBCqZ.jpg)

**Comment by mofosyne** [comment]
Great work! Thanks for the nice chat. Added your works to https://github.com/mofosyne/arduino-gameboy-printer-emulator/blob/master/showcase/showcase.md so closing this ticket now :)
