### ISSUE TITLE
Issues solved for Tsuri Seensei 2

### ISSUE THREAD

**Issue by Raphael-Boichot** [mofosyne/arduino-gameboy-printer-emulator#57]
Hello.

Here is a bug fix for two issues with Tsuri Sensei 2:
- During the printing, you can change the image on screen, it sends an INIT command to the serial that enters en infinite loop because busy state is not set to zero (FIXED).
- You must escape (no choice) the printing menu by sending an ABORT command. It was not correctly taken into account in the emulator due to a redundancy that leads to an infinite loop.
This file fixes the two issues:
[gbp_serial_io.cpp.txt](https://github.com/mofosyne/arduino-gameboy-printer-emulator/files/7019464/gbp_serial_io.cpp.txt)

**Comment by mofosyne** [comment]
Corrections added to https://github.com/mofosyne/arduino-gameboy-printer-emulator/commit/e6f67eb4753544ee2d90a4735bc112861ee3962d thanks. Tested and working with gameboy camera
