### ISSUE TITLE
Update Documentation With Information On Using The Printer Interface Feature

### ISSUE THREAD

**Issue by mofosyne** [mofosyne/arduino-gameboy-printer-emulator#66]
https://github.com/mofosyne/arduino-gameboy-printer-emulator/pull/63

**Comment by Raphael-Boichot** [comment]
I think this one is fixed

**Comment by mofosyne** [comment]
Yup, https://github.com/mofosyne/arduino-gameboy-printer-emulator?tab=readme-ov-file#download-via-android-app-and-use-the-arduino-as-a-generic-output-interface-for-the-game-boy-printer-external-project all good. Thanks for the reminder
